FROM php:5.6-apache

RUN apt update && apt-get install -y --no-install-recommends wget gpg g++ libicu57 \
    libicu-dev libpq-dev libzip-dev imagemagick netcat dirmngr \
    && ln -fs /usr/lib/x86_64-linux-gnu/libzip.so /usr/lib/ \
    && docker-php-ext-install intl zip mbstring opcache fileinfo \
    && docker-php-ext-install mysqli \
    && docker-php-ext-install pgsql \
    && apt-get purge -y --auto-remove g++ libicu-dev libzip-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pear install mail net_smtp
RUN a2enmod rewrite

RUN gpg --keyserver pool.sks-keyservers.net --recv-keys \
    441276E9CCD15F44F6D97D18C119E1A64D70938E \
    41B2ABE817ADD3E52BDA946F72BC1C5D23107F8A \
    162432D9E81C1C618B301EECEE1F663462D84F01 \
    1D98867E82982C8FE0ABC25F9B69B3109D3BB7B0 \
    3CEF8262806D3F0B6BA1DBDD7956EE477F901A30 \
    280DB7845A1DCAC92BB5A00A946B02565DC00AA7

COPY config/php.ini /usr/local/etc/php/conf.d/mediawiki.ini
COPY config/mediawiki.conf /etc/apache2/

RUN echo "Include /etc/apache2/mediawiki.conf" >> /etc/apache2/apache2.conf

COPY scripts/docker-base-entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["apache2-foreground"]
